---
version: '2.1'

services:
  pw_manager_bot:
    container_name: password_manager
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python3 -u main.py
    depends_on:
      db:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: always
    volumes:
      - ./app:/app

  db:
    container_name: pw-manager-db
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
    image: postgres:14.1-alpine
    ports:
      - '4001:5432'
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
